name: CI  
  
on:  
  push:  
    branches:  
      - master # 确保与你的默认分支名称匹配  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v2  
  
      # 如果需要安装Hexo和依赖，可以添加这一步  
      - name: Setup Node.js environment  
        uses: actions/setup-node@v2  
        with:  
          node-version: '20' # 使用适合你Hexo项目的Node.js版本  
  
      # 安装Hexo和依赖项（如果package.json已经包含）  
      - name: Install dependencies  
        run: npm install  
  
      # 生成Hexo站点  
      - name: Build Hexo site  
        run: npm run build  
  
      # 部署到GitHub Pages  
      - name: Deploy to GitHub Pages  
        uses: JamesIves/github-pages-deploy-action@v4.2.5  
        with:  
          branch: master # 部署分支，通常是main或master  
          folder: public # Hexo生成的静态文件所在的文件夹  
          access_token: ${{ secrets.ACCESS_TOKEN }} # 你的GitHub个人访问令牌
          
